services:
  pgvector-db:
    image: ankane/pgvector:latest
    container_name: mcp-pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mcp_uren_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verysecret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vmos -d mcp_uren_db"]
      interval: 5s
      timeout: 5s
      retries: 5