server:
  compression:
    enabled: false # Disable response compression for streaming filling on frontend

spring:
  application:
    name: spring-gemini-ai

  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
        streamable-http:
          connections:
            server1:
              url: http://localhost:8085
        toolcallback:
          enabled: true
    model:
      chat: vertexai
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID:ai-mcp-vmos}
          location: europe-west1
        embedding:
          enabled: true
          options:
            model: text-embedding-004  # Or textembedding-gecko@003
          project-id: ${GEMINI_PROJECT_ID:ai-mcp-vmos}
          location: europe-west1

#server:
#  port: 9191
logging:
  level:
    root: info
#    org.springframework.ai.vectorstore: DEBUG # Handig voor je demo om de SQL te zien
    org.springframework.ai.mcp: TRACE
    org.springframework.ai.vertexai.gemini: DEBUG